try{;(function(){var aC=window._vwo_code;if(aC){window._vwo_j_e=window._vwo_j_e||0;if(window._vwo_j_e==1){window._vwo_mt="dupCode";clearTimeout(window._vwo_settings_timer);if(window.VWO&&window.VWO._&&window.VWO._.bIE){window._vwo_code.finish()}return}if(window._vwo_j_e==-1){window._vwo_j_e=1}}window._vwo_mt="live";try{window._vwo_tm="";var getMode=function(e){var n;if(window.name.indexOf(e)>-1){n=window.name}else{n=window.location.search.match("_vwo_m=([^&]*)");n=n&&n[1]}return n&&JSON.parse(decodeURIComponent(n))};if(window.name.indexOf("_vis_heatmap")>-1||window.name.indexOf("_vis_editor")>-1||getMode("_vwo_cc")||window.name.indexOf("_vis_preview")>-1){window._vwo_mt=window.name}else if(window._vwo_tm.length){window._vwo_mt=window._vwo_tm}else if(location.href.indexOf("_vis_opt_preview_combination")!==-1&&location.href.indexOf("_vis_test_id")!==-1){window._vwo_mt="sharedPreview"}if(window._vwo_mt!=="live"){if(!getMode("_vwo_cc")){_vwo_code.load('https://dev.visualwebsiteoptimizer.com/j.php?mode=' + encodeURIComponent(window._vwo_mt) + '&a=338524&f=1&u=' + encodeURIComponent(window._vis_opt_url||document.URL));}else{(function(){window._vwo_code&&window._vwo_code.finish();_vwo_ccc={u:"/j.php?a=338524&u=https%3A%2F%2Fblog.logrocket.com%2Fadd-firebase-to-your-flutter-app-with-flutterfire-plugins%2F&f=1&r=0.19145669736454862"};var s=document.createElement("script");s.src="https://app.vwo.com/visitor-behavior-analysis/dist/codechecker/cc.min.js?r="+Math.random();document.head.appendChild(s)})()}}}catch(e){var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?s=mode_det&e="+encodeURIComponent(e&&e.stack&&e.stack.substring(0,1e3));aC&&window._vwo_code.finish()}})();if(window._vwo_mt==='live'){;window.VWO = window.VWO || []; window.VWO.push(['modifyClickPauseTime', { time: 0 }]);_vwo_code.sT=_vwo_code.finished();(function(c,a,e,d,b,z){function f(a,b,d){e.cookie=a+"="+b+"; expires="+new Date(864e5*d+ +new Date).toGMTString()+"; domain="+c+"; path=/"}-1==e.cookie.indexOf("_vis_opt_out")&&-1==d.location.href.indexOf("vwo_opt_out=1")&&(a=e.cookie.replace(/(?:(?:^|.*;\s*)_vwo_uuid_v2\s*=\s*([^;]*).*$)|^.*$/,"$1")||a,a=a.split("|"),b=new Image,c=d.location.hostname.replace(/^www\./,"")||c,b.src="https://dev.visualwebsiteoptimizer.com/v.gif?cd="+(window._vis_opt_cookieDays||0)+"&a=338524&d="+encodeURIComponent(c)+"&u="+a[0]+"&h="+a[1]+"&t="+z+"&r="+Math.random(),d.vwo_iehack_queue=[b],f("_vwo_uuid_v2",a.join("|"),366))})("logrocket.com","DF2E0367FF3EB0B3A76086F8871E5CF61|7b211b2f55005efcca6a71d45d01cebf",document,window,0,_vwo_code.sT);var _vwo_acc_id=338524;
clearTimeout(_vwo_settings_timer);_vwo_exp_ids=[],_vwo_exp={};window.VWO=window.VWO||[];
window.VWO.data={"noSS":false,"ts":1659211473};window.VWO.featureInfo={};_vwo_exp_ids.push('134');_vwo_exp['134']={"version":4,"ep":1658427663000,"clickmap":0,"globalCode":{},"isEventMigrated":true,"type":"VISUAL_AB","status":"RUNNING","pc_traffic":100,"name":"Blog Wired Style Newsletter Plug - July 2022","manual":false,"urlRegex":"^.*blog.*$","exclude_url":"^.*Q122_blogrm.*$|^https\\:\\\/\\\/blog\\.logrocket\\.com\\\/?(?:[\\?#].*)?$|^.*product\\-management.*$|^.*\\\/logrocket\\-interviews\\-whole\\-engineer.*$|^.*\\\/logrocket\\-interviews\\-keeping\\-teams\\-together\\-apart.*$|^.*\\\/logrocket\\-interviews\\-is\\-scoping\\-more\\-trouble\\-than\\-its\\-worth.*$|^.*\\\/announcing\\-logrocket\\-issue\\-management.*$|^.*\\\/react\\-why\\-you\\-should\\-continue\\-using\\-it.*$|^.*\\\/wmr\\-the\\-swiss\\-army\\-knife\\-for\\-web\\-apps.*$|^.*\\\/logging\\-error\\-management\\-best\\-practices\\-ssr\\-apps.*$|^.*\\\/rethinking\\-mobile\\-app\\-monitoring.*$","multiple_domains":0,"segment_code":"true","ss":null,"ibe":0,"muts":{"post":{"enabled":true,"refresh":true}},"sections":{"1":{"path":"","variations":{"1":"[]","2":"[{\"js\":\"var el,ctx=vwo_$(x);\\n\\\/*vwo_debug log(\\\"remove\\\",\\\".code-block-54\\\"); vwo_debug*\\\/(el=vwo_$(\\\".code-block-54\\\")).vwoCss({display:\\\"none !important\\\"});\",\"xpath\":\".code-block-54\"}]"},"segment":{"1":1,"2":1},"segmentObj":[]}},"varSegAllowed":false,"combs":{"1":0.5,"2":0.5},"comb_n":{"1":"Variation-1","2":"Control"},"goals":{"1":{"urlRegex":"(https:\\\/\\\/logrocket\\.com.*)|(https:\\\/\\\/www2\\.logrocket\\.com.*)","excludeUrl":"","type":"SEPARATE_PAGE"},"2":{"url":".code-block-54 a","type":"CLICK_ELEMENT"},"203":{"urlRegex":"https:\\\/\\\/app\\.logrocket\\.com.*","excludeUrl":"","type":"CUSTOM_GOAL"},"204":{"urlRegex":"https:\\\/\\\/app\\.logrocket\\.com.*","excludeUrl":"","type":"CUSTOM_GOAL"},"209":{"urlRegex":"^.*lp\\.logrocket\\.com.*$","excludeUrl":"","type":"CUSTOM_GOAL"}},"pgre":true,"ps":false};var vwoCode = window._vwo_code; if(vwoCode.filterConfig && vwoCode.filterConfig.filterTime==='balanced'){ vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay() };var _vwo_style=document.getElementById('_vis_opt_path_hides'),_vwo_css= window._vwo_el_style || '{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;} :root {--vwo-el-opacity:0 !important;--vwo-el-filter:alpha(opacity=0) !important;--vwo-el-bg:none !important;}';
var _vwo_text=".code-block-54"+_vwo_css;if(_vwo_style){if(_vwo_style.styleSheet){_vwo_style.styleSheet.cssText=_vwo_text;}else{var _vwo_textnode=document.createTextNode(_vwo_text);_vwo_style.appendChild(_vwo_textnode);_vwo_style.removeChild(_vwo_style.childNodes[0]);}}const commonWrapper=function({valuesGetter:valuesGetter=function(){return{}},valuesSetter:valuesSetter=function(){},verifyData:verifyData=function(){return{}}}){const pollInterval=100;const timeout=5e3;return function(){let accountIntegrationSettings={};let _interval=null;function waitForAnalyticsVariables(){accountIntegrationSettings=valuesGetter();if(accountIntegrationSettings&&verifyData()){valuesSetter(accountIntegrationSettings);verifyData();return 1}return 0}let currentTime=0;_interval=setInterval((function(){currentTime=currentTime||performance.now();const result=waitForAnalyticsVariables();if(result||performance.now()-currentTime>=timeout){clearInterval(_interval)}}),pollInterval)}};(function(){var VWOOmniTemp={};window.VWOOmni=window.VWOOmni||{};                    for (var key in VWOOmniTemp) {
                        window.VWOOmni[key] = VWOOmniTemp[key];
                    }
                ;})();    (function(){window.VWO=window.VWO||[];var pollInterval=100;
        var _vis_data={};
        var intervalObj={};
        var analyticsTimerObj={};
        var experimentListObj={};window.VWO.push(["onVariationApplied",function(data){if(!data){return}var expId=data[1],variationId=data[2];if(expId&&variationId&&["VISUAL_AB","VISUAL","SPLIT_URL"].indexOf(window._vwo_exp[expId].type)>-1){}}])})();
    window.VWO.data.vi = window.VWO.data.vi || {"os":"Windows","de":"Other","dt":"desktop","br":"Edge"};
window.VWO.push(['enableSPA']);
VWO.load_co=function(a){var b=document.createElement('script');b.src=a;b.crossOrigin='anonymous';b.fetchPriority='high';b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};document.getElementsByTagName('head')[0].appendChild(b);}
var _vwo_cookieDomain = 'logrocket.com', _vwo_uuid = 'DF2E0367FF3EB0B3A76086F8871E5CF61';window.VWO=window.VWO||[];VWO._=VWO._||{};var _vis_opt_file = _vwo_code.use_existing_jquery() ? '7.0/vanj-3a8c03cc83fd9c554b5af6e1cc1ffa80.js' : '7.0/va-3a8c03cc83fd9c554b5af6e1cc1ffa80.js',_vwo_library_timer = setTimeout(function () {var vwoCode = _vwo_code; vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay(); vwoCode.finish()},vwoCode.library_tolerance()),_vis_opt_lib = (typeof _vis_opt_lib=='undefined')?'https://dev.visualwebsiteoptimizer.com/'+_vis_opt_file:_vis_opt_lib;VWO.load_co(_vis_opt_lib);window.VWO.data.as = "r2.visualwebsiteoptimizer.com";;window.VWO=window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};; 
window.VWO = window.VWO || [];
window.VWO.data = window.VWO.data || {};
VWO.data.content={"fns":{"list":{"vn":1,"args":{"1":{}}}}};;window.VWO = window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};VWO._.ac.dNdOfst=1000;}}catch(e){_vwo_code.finish(); _vwo_code.removeLoaderAndOverlay && _vwo_code.removeLoaderAndOverlay(); var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?a=338524&s=j.php&e="+encodeURIComponent(e && e.message && e.message.substring(0,1000))+"&url"+encodeURIComponent(window.location.href)}